openapi: 3.0.0
info:
  title: Expense Tracker API
  description: API documentation for the Expense Tracker backend.
  version: 1.0.0
servers:
  - url: http://localhost:5000/api
paths:
  /auth/register:
    post:
      summary: User Register
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                name:
                  type: string
      responses:
        '201':
          description: Successfully created
        '400':
          description: Bad request
  
  /auth/login:
      post:
        summary: User login
        tags:
          - Auth
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: string
                  password:
                    type: string
        responses:
          '200':
            description: Successful login
          '401':
            description: Unauthorized

  /expense/expense:
      post:
        summary: Create Expense/Income
        tags:
          - Expense
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  title:
                    type: string
                  amount:
                    type: number
                  type:
                    type: string
                  category:
                    type: string
                  date:
                    type: string
        responses:
          '201':
            description: Expense/Income added successfully
          '401':
            description: Unauthorized
          '500':
            description: Internal server error

